# Generated by Django 3.1.7 on 2021-02-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('R', 'Reviewed'), ('N', 'Not Reviewed'), ('E', 'Error'), ('A', 'Accepted')], default='R', max_length=50),
            preserve_default=False,
        ),
    ]
